server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: blog-backend
    static_configs:
      - targets: [localhost]
        labels:
          job: blog
          app: backend
          __path__: /app/my-blog/backend/logs/*.log
  - job_name: blog-frontend
    static_configs:
      - targets: [localhost]
        labels:
          job: blog
          app: frontend
          __path__: /app/my-blog/frontend/logs/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} [+-]\d{4}) \| (?P<content>.*)'
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05 -0700"
      - output:
          source: content
  - job_name: LearningCollector_logs
    static_configs:
      - targets: [localhost]
        labels:
          job: LearningCollector
          __path__: /app/LearningCollector/log/promtail_feed.jsonl
    pipeline_stages:
      - json:
          expressions:
            level: level
            event: event
            component: component
      - labels:
          level:
          event:
          component:
  - job_name: docker_logs
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/log/trivy/*.log;/var/log/trivy/*.json
  - job_name: syslog
    static_configs:
      - targets: [localhost]
        labels:
          job: syslog
          __path__: /var/log/syslog
